import React from 'react';
import {
  Check,
  X,
  ExternalLink,
  FileText,
  Bell,
  ShieldCheck,
  HelpCircle,
  Clock,
  IndianRupee,
  AlertTriangle,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { CategoryPill } from '@/components/intelligence/primitives';
import type { ClaimAction, ClaimActionKind } from '@/hooks/intelligence';

/**
 * Sprint Intelligence Layer, Wave 11 — RuleSourcedActionRow.
 *
 * Row variant rendered when `action.payload.source_rule_id` is present —
 * i.e. the action was generated by ActionTemplatingService (Wave 11) from a
 * failed insurance_rules row, rather than the generic Wave 3C path. Surfaces
 * the rule lineage, the estimated deduction (if any), and the required
 * documents as pills.
 *
 * Kept as a sibling component (not an extension of ActionRow) because the
 * extra metadata cells push past the 30-line delta we're comfortable adding
 * to ActionRow.
 */
export interface RuleSourcedActionRowProps {
  action: ClaimAction;
  onAck: (id: string, response: Record<string, any>) => Promise<void> | void;
  onRequestDecline: (action: ClaimAction) => void;
  busy?: boolean;
  className?: string;
}

const KIND_ICON: Record<string, React.ComponentType<{ className?: string }>> = {
  request_doc: FileText,
  notify_ops: Bell,
  approval_request: ShieldCheck,
  rule_clarification: HelpCircle,
};

const KIND_LABEL: Record<string, string> = {
  request_doc: 'Document request',
  notify_ops: 'Ops notification',
  approval_request: 'Approval request',
  rule_clarification: 'Rule clarification',
};

const PRIORITY_PALETTE: Record<string, string> = {
  critical: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
  high: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
  normal: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  low: 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400',
};

function relTime(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diffMs / 60_000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
}

function formatINR(n: number): string {
  try {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(n);
  } catch {
    return `₹${Math.round(n).toLocaleString('en-IN')}`;
  }
}

export const RuleSourcedActionRow: React.FC<RuleSourcedActionRowProps> = ({
  action,
  onAck,
  onRequestDecline,
  busy = false,
  className,
}) => {
  const kind = action.kind as ClaimActionKind | 'rule_clarification';
  const Icon = KIND_ICON[kind] ?? Bell;
  const title = (action.payload?.title as string | undefined) ?? KIND_LABEL[kind] ?? 'Action';
  const summary = (action.payload?.summary as string | undefined) ?? '';
  const deepLink = action.payload?.deep_link as string | undefined;
  const ruleId = action.payload?.source_rule_id as string | undefined;
  const ruleSetId = action.payload?.source_rule_set_id as string | undefined;
  const deduction = Number(action.payload?.estimated_deduction_amount ?? 0);
  const requiredDocs = (action.payload?.required_documents as string[] | undefined) ?? [];
  const priority = (action.payload?.priority as string | undefined) ?? 'normal';
  const severity = action.payload?.severity as string | undefined;

  const handleAck = async () => {
    const response = kind === 'approval_request' ? { decision: 'approved' } : {};
    await onAck(action.id, response);
  };

  return (
    <tr
      className={cn(
        'border-b border-slate-200 dark:border-slate-800',
        'hover:bg-slate-50 dark:hover:bg-slate-900/50',
        className,
      )}
    >
      <td className="px-3 py-3 align-top">
        <div className="flex items-start gap-2">
          <Icon
            className="size-4 mt-0.5 text-slate-500 dark:text-slate-400 shrink-0"
            aria-hidden
          />
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <CategoryPill category={KIND_LABEL[kind] ?? kind} size="xs" />
              {priority && (
                <span
                  className={cn(
                    'inline-flex items-center rounded-md font-medium text-[10px] px-1.5 py-0.5',
                    PRIORITY_PALETTE[priority] ?? PRIORITY_PALETTE.normal,
                  )}
                >
                  {priority}
                </span>
              )}
              {severity && severity.toUpperCase() === 'CRITICAL' && (
                <span className="inline-flex items-center gap-1 text-[10px] text-red-700 dark:text-red-300">
                  <AlertTriangle className="size-3" />
                  Critical
                </span>
              )}
              <span className="text-sm font-medium text-slate-900 dark:text-slate-100 truncate">
                {title}
              </span>
            </div>
            {summary && (
              <p className="text-xs text-slate-600 dark:text-slate-400 mt-1 whitespace-pre-line line-clamp-4">
                {summary}
              </p>
            )}
            {/* Required documents pills */}
            {requiredDocs.length > 0 && (
              <div className="mt-2 flex flex-wrap items-center gap-1">
                <span className="text-[10px] uppercase tracking-wide text-slate-400 dark:text-slate-500">
                  Docs
                </span>
                {requiredDocs.map((d) => (
                  <CategoryPill key={d} category={d} size="xs" />
                ))}
              </div>
            )}
            {/* Rule lineage + deduction */}
            <div className="mt-2 flex items-center gap-3 text-[11px] text-slate-500 dark:text-slate-400">
              {ruleId && (
                <a
                  href={
                    ruleSetId
                      ? `/superadmin/rules/${ruleSetId}#${ruleId}`
                      : `#${ruleId}`
                  }
                  className="inline-flex items-center gap-1 hover:underline"
                  title="Open rule definition"
                >
                  <span className="font-mono">{ruleId}</span>
                </a>
              )}
              {deduction > 0 && (
                <span className="inline-flex items-center gap-1 text-amber-700 dark:text-amber-300 font-medium">
                  <IndianRupee className="size-3" />
                  {formatINR(deduction)} at risk
                </span>
              )}
            </div>
          </div>
        </div>
      </td>
      <td className="px-3 py-3 align-top">
        {deepLink ? (
          <a
            href={deepLink}
            className="text-xs text-indigo-600 dark:text-indigo-400 hover:underline inline-flex items-center gap-1"
          >
            <ExternalLink className="size-3" />
            {action.claim_id.slice(0, 8)}
          </a>
        ) : (
          <code className="text-xs text-slate-500 dark:text-slate-400">
            {action.claim_id.slice(0, 8)}
          </code>
        )}
      </td>
      <td className="px-3 py-3 align-top">
        <div className="text-xs text-slate-500 dark:text-slate-400 inline-flex items-center gap-1">
          <Clock className="size-3" />
          {relTime(action.created_at)}
        </div>
      </td>
      <td className="px-3 py-3 align-top">
        <div className="flex items-center gap-2 justify-end">
          <Button
            size="sm"
            variant="default"
            onClick={handleAck}
            disabled={busy}
            className="gap-1"
          >
            <Check className="size-3.5" />
            {kind === 'approval_request' ? 'Approve' : 'Ack'}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => onRequestDecline(action)}
            disabled={busy}
            className="gap-1 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/40"
          >
            <X className="size-3.5" />
            Decline
          </Button>
        </div>
      </td>
    </tr>
  );
};

export default RuleSourcedActionRow;
