-- ==========================================================================
-- 020 — document_field_schemas (per-doc-category extraction schema)
-- ==========================================================================
-- Applied by src/schema/run-seeds.cjs, which owns the transaction and records
-- this file's sha256 in hospital.seed_applications. Editing the file changes
-- that checksum, which is exactly what makes the next `npm run seed` re-apply
-- it. See seeds/README.md for the authoring rules the CI guard enforces.
--
-- This is a DECLARATIVE snapshot of the desired catalog, not a replay of
-- history: it was generated from a database that had run every migration in
-- order, so it is the union of the sources below with every later rename,
-- relabel and correction already folded in.
--
-- Historical sources (left untouched in migrations/, which production is
-- already stamped for):
--   048_field_schemas_for_kyc_and_reports.sql
--   051_field_schemas_for_clinical_categories.sql
--   053_field_schemas_for_missing_categories.sql
--   054_field_schemas_round_2.sql
--   059_aadhaar_taxonomy_and_pmjay_categories.sql
--   063_missing_clinical_schemas.sql
--
-- Every source migration used ON CONFLICT DO NOTHING, which is why a corrected
-- field label, type or extraction priority never reached an environment that had
-- already run them. This layer uses DO UPDATE so corrections converge.
-- ==========================================================================

INSERT INTO hospital.document_field_schemas
    (doc_category, field_key, field_label, field_type, is_required, enum_values, reference_category, extraction_priority, schema_version) VALUES
    ('aadhaar_back', 'aadhaar_number', 'Aadhaar Number', 'text', true, NULL, NULL, 10, 1),
    ('aadhaar_back', 'address', 'Full Address', 'text', true, NULL, NULL, 20, 1),
    ('aadhaar_back', 'parent_or_spouse_name', 'Parent / Spouse Name', 'text', false, NULL, NULL, 30, 1),
    ('aadhaar_back', 'pin_code', 'PIN Code', 'text', false, NULL, NULL, 40, 1),
    ('aadhaar_back', 'state', 'State', 'text', false, NULL, NULL, 50, 1),
    ('aadhaar_card', 'holder_name', 'Holder Name', 'text', true, NULL, NULL, 10, 1),
    ('aadhaar_card', 'aadhaar_number', 'Aadhaar Number', 'text', true, NULL, NULL, 20, 1),
    ('aadhaar_card', 'date_of_birth', 'Date of Birth', 'date', false, NULL, NULL, 30, 1),
    ('aadhaar_card', 'gender', 'Gender', 'enum', false, '["male", "female", "other"]'::jsonb, NULL, 40, 1),
    ('aadhaar_card', 'address', 'Address', 'text', false, NULL, NULL, 50, 1),
    ('aadhaar_front', 'full_name', 'Full Name', 'text', true, NULL, NULL, 10, 1),
    ('aadhaar_front', 'aadhaar_number', 'Aadhaar Number', 'text', true, NULL, NULL, 20, 1),
    ('aadhaar_front', 'date_of_birth', 'Date of Birth', 'date', false, NULL, NULL, 30, 1),
    ('aadhaar_front', 'gender', 'Gender', 'enum', false, '["M", "F", "O"]'::jsonb, NULL, 40, 1),
    ('aadhaar_front', 'year_of_birth', 'Year of Birth', 'number', false, NULL, NULL, 50, 1),
    ('abha_card', 'abha_number', 'ABHA Number (14 digits)', 'text', true, NULL, NULL, 10, 1),
    ('abha_card', 'abha_address', 'ABHA Address', 'text', false, NULL, NULL, 20, 1),
    ('abha_card', 'holder_name', 'Holder Name', 'text', true, NULL, NULL, 30, 1),
    ('abha_card', 'date_of_birth', 'Date of Birth', 'date', false, NULL, NULL, 40, 1),
    ('abha_card', 'gender', 'Gender', 'enum', false, '["male", "female", "other"]'::jsonb, NULL, 50, 1),
    ('abha_card', 'issued_date', 'Issued Date', 'date', false, NULL, NULL, 60, 1),
    ('admission_notes', 'admission_date', 'Admission Date', 'date', true, NULL, NULL, 10, 1),
    ('admission_notes', 'admission_time', 'Admission Time', 'text', false, NULL, NULL, 15, 1),
    ('admission_notes', 'admission_type', 'Admission Type', 'enum', false, '["EMERGENCY", "ELECTIVE", "PLANNED", "TRANSFER"]'::jsonb, NULL, 20, 1),
    ('admission_notes', 'admitting_doctor', 'Admitting Doctor', 'text', false, NULL, NULL, 30, 1),
    ('admission_notes', 'admission_diagnosis', 'Admission Diagnosis', 'text', true, NULL, NULL, 40, 1),
    ('admission_notes', 'chief_complaints', 'Chief Complaints', 'text', false, NULL, NULL, 50, 1),
    ('admission_notes', 'history_of_present_illness', 'History of Present Illness', 'text', false, NULL, NULL, 60, 1),
    ('admission_notes', 'past_history', 'Past History', 'text', false, NULL, NULL, 70, 1),
    ('admission_notes', 'examination_findings', 'Examination Findings', 'text', false, NULL, NULL, 80, 1),
    ('admission_notes', 'vitals_on_admission', 'Vitals on Admission', 'text', false, NULL, NULL, 90, 1),
    ('admission_notes', 'plan', 'Initial Plan', 'text', false, NULL, NULL, 100, 1),
    ('anaesthesia_consent', 'surgery_date', 'Surgery Date', 'date', false, NULL, NULL, 10, 1),
    ('anaesthesia_consent', 'duration_minutes', 'Anaesthesia Duration (mins)', 'number', false, NULL, NULL, 20, 1),
    ('anaesthesia_consent', 'anaesthesia_type', 'Anaesthesia Type', 'enum', false, '["GENERAL", "SPINAL", "EPIDURAL", "REGIONAL", "LOCAL", "SEDATION", "COMBINED"]'::jsonb, NULL, 30, 1),
    ('anaesthesia_consent', 'anaesthetist', 'Anaesthetist', 'text', false, NULL, NULL, 40, 1),
    ('anaesthesia_consent', 'asa_grade', 'ASA Physical Status', 'enum', false, '["ASA_I", "ASA_II", "ASA_III", "ASA_IV", "ASA_V", "ASA_VI"]'::jsonb, NULL, 50, 1),
    ('anaesthesia_consent', 'pre_anaesthetic_findings', 'Pre-anaesthetic Findings', 'text', false, NULL, NULL, 60, 1),
    ('anaesthesia_consent', 'consent_signed_by', 'Consent Signed By', 'text', false, NULL, NULL, 70, 1),
    ('anaesthesia_consent', 'consent_date', 'Consent Date', 'date', false, NULL, NULL, 80, 1),
    ('blood_test_reports', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 10, 1),
    ('blood_test_reports', 'patient_age', 'Patient Age (years)', 'number', false, NULL, NULL, 15, 1),
    ('blood_test_reports', 'patient_sex', 'Patient Sex', 'enum', false, '["male", "female", "other"]'::jsonb, NULL, 16, 1),
    ('blood_test_reports', 'study_date', 'Sample Collection Date', 'date', false, NULL, NULL, 20, 1),
    ('blood_test_reports', 'lab_name', 'Lab / Imaging Centre', 'text', false, NULL, NULL, 25, 1),
    ('blood_test_reports', 'reporting_doctor', 'Reporting Pathologist', 'text', false, NULL, NULL, 30, 1),
    ('blood_test_reports', 'panel_type', 'Panel Type (e.g. CBC, LFT, KFT, Lipid)', 'text', false, NULL, NULL, 35, 1),
    ('blood_test_reports', 'haemoglobin', 'Haemoglobin (g/dL)', 'text', false, NULL, NULL, 40, 1),
    ('blood_test_reports', 'tlc', 'Total Leukocyte Count', 'text', false, NULL, NULL, 41, 1),
    ('blood_test_reports', 'platelets', 'Platelets (lakh/mcL)', 'text', false, NULL, NULL, 42, 1),
    ('blood_test_reports', 'creatinine', 'Creatinine (mg/dL)', 'text', false, NULL, NULL, 50, 1),
    ('blood_test_reports', 'urea', 'Urea (mg/dL)', 'text', false, NULL, NULL, 51, 1),
    ('blood_test_reports', 'bilirubin_total', 'Total Bilirubin', 'text', false, NULL, NULL, 52, 1),
    ('blood_test_reports', 'sgot_ast', 'SGOT / AST', 'text', false, NULL, NULL, 53, 1),
    ('blood_test_reports', 'sgpt_alt', 'SGPT / ALT', 'text', false, NULL, NULL, 54, 1),
    ('blood_test_reports', 'glucose_fasting', 'Glucose (Fasting)', 'text', false, NULL, NULL, 55, 1),
    ('blood_test_reports', 'hba1c', 'HbA1c (%)', 'text', false, NULL, NULL, 56, 1),
    ('blood_test_reports', 'abnormal_flags', 'Abnormal / Flagged Values', 'text', false, NULL, NULL, 80, 1),
    ('blood_test_reports', 'reference_lab_no', 'Lab / Reference Number', 'text', false, NULL, NULL, 90, 1),
    ('consent', 'consent_date', 'Consent Date', 'date', false, NULL, NULL, 10, 1),
    ('consent', 'consent_type', 'Consent Type', 'enum', false, '["surgery", "anaesthesia", "blood_transfusion", "procedure", "admission", "general"]'::jsonb, NULL, 20, 1),
    ('consent', 'procedure_described', 'Procedure Described', 'text', false, NULL, NULL, 30, 1),
    ('consent', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 40, 1),
    ('consent', 'signed_by', 'Signed By', 'text', false, NULL, NULL, 50, 1),
    ('consent', 'relationship_to_patient', 'Relationship to Patient', 'text', false, NULL, NULL, 60, 1),
    ('consent', 'witness_name', 'Witness Name', 'text', false, NULL, NULL, 70, 1),
    ('ct_scan_reports', 'study_date', 'Study Date', 'date', true, NULL, NULL, 10, 1),
    ('ct_scan_reports', 'body_part', 'Body Part / Anatomy', 'text', true, NULL, NULL, 20, 1),
    ('ct_scan_reports', 'clinical_indication', 'Clinical Indication', 'text', false, NULL, NULL, 30, 1),
    ('ct_scan_reports', 'contrast_used', 'Contrast Used', 'enum', false, '["none", "iv_contrast", "oral_contrast", "both"]'::jsonb, NULL, 40, 1),
    ('ct_scan_reports', 'findings', 'Findings', 'text', true, NULL, NULL, 50, 1),
    ('ct_scan_reports', 'impression', 'Impression / Conclusion', 'text', true, NULL, NULL, 60, 1),
    ('ct_scan_reports', 'ordering_physician', 'Ordering Physician', 'text', false, NULL, NULL, 70, 1),
    ('ct_scan_reports', 'reporting_radiologist', 'Reporting Radiologist', 'text', false, NULL, NULL, 80, 1),
    ('diagnosis_summary', 'primary_diagnosis', 'Primary Diagnosis', 'text', true, NULL, NULL, 10, 1),
    ('diagnosis_summary', 'icd_code_candidate', 'ICD Code Candidate', 'text', false, NULL, NULL, 20, 1),
    ('diagnosis_summary', 'comorbidities', 'Comorbidities', 'text', false, NULL, NULL, 30, 1),
    ('diagnosis_summary', 'proposed_treatment', 'Proposed Treatment', 'text', false, NULL, NULL, 40, 1),
    ('diagnosis_summary', 'justification', 'Justification', 'text', false, NULL, NULL, 50, 1),
    ('discharge_slip', 'admission_date', 'Admission Date', 'date', true, NULL, NULL, 10, 1),
    ('discharge_slip', 'discharge_date', 'Discharge Date', 'date', true, NULL, NULL, 20, 1),
    ('discharge_slip', 'primary_diagnosis', 'Primary Diagnosis', 'text', true, NULL, NULL, 30, 1),
    ('discharge_slip', 'treating_doctor', 'Treating Doctor', 'text', false, NULL, NULL, 40, 1),
    ('discharge_slip', 'room_category', 'Room Category', 'enum', false, '["general", "semi_private", "private", "icu", "iccu", "nicu"]'::jsonb, NULL, 50, 1),
    ('discharge_slip', 'total_amount', 'Total Amount', 'money', false, NULL, NULL, 60, 1),
    ('discharge_summary', 'admission_date', 'Admission Date', 'date', true, NULL, NULL, 10, 1),
    ('discharge_summary', 'discharge_date', 'Discharge Date', 'date', true, NULL, NULL, 20, 1),
    ('discharge_summary', 'primary_diagnosis', 'Primary Diagnosis', 'text', true, NULL, NULL, 30, 1),
    ('discharge_summary', 'secondary_diagnoses', 'Secondary Diagnoses', 'text', false, NULL, NULL, 40, 1),
    ('discharge_summary', 'presenting_complaints', 'Presenting Complaints', 'text', false, NULL, NULL, 50, 1),
    ('discharge_summary', 'treatment_given', 'Treatment Given', 'text', false, NULL, NULL, 60, 1),
    ('discharge_summary', 'procedure_performed', 'Procedure Performed', 'text', false, NULL, NULL, 70, 1),
    ('discharge_summary', 'condition_at_discharge', 'Condition at Discharge', 'text', false, NULL, NULL, 80, 1),
    ('discharge_summary', 'follow_up_advice', 'Follow-up Advice', 'text', false, NULL, NULL, 90, 1),
    ('discharge_summary', 'treating_doctor', 'Treating Doctor', 'text', false, NULL, NULL, 100, 1),
    ('discharge_summary', 'discharge_medications', 'Discharge Medications', 'text', false, NULL, NULL, 110, 1),
    -- final_bill — the itemised hospital bill, and the highest-value document
    -- in a claim. It had NO rows here until 2026-09-14, which meant
    -- docExtractor took its `fieldRows.length === 0` branch, stamped
    -- extractor_model='no_schema', made no model call, and skipped the bill
    -- entirely. `line_items` is deliberately NOT a row: lineItems
    -- .buildLineItemsPromptBlock injects it for every LINE_ITEM_CATEGORIES
    -- member (which already includes final_bill), but only once fieldRows is
    -- non-empty — which is precisely what these rows fix.
    -- Shape mirrors pharmacy_bill (the neighbouring money document) plus the
    -- admission/discharge dates the harmoniser reconciles against, and the
    -- structured identifiers (uhid, ipd_number) the identity gate keys on.
    -- `gross_amount` / `net_amount` are named to match harmonisation
    -- .STATED_TOTAL_KEYS, where net_amount is the most authoritative total.
    ('final_bill', 'bill_number',      'Bill / Invoice Number',   'text',   false, NULL, NULL,  10, 1),
    ('final_bill', 'bill_date',        'Bill Date',               'date',   false, NULL, NULL,  20, 1),
    ('final_bill', 'patient_name',     'Patient Name',            'text',   false, NULL, NULL,  30, 1),
    ('final_bill', 'uhid',             'UHID / Registration No',  'text',   false, NULL, NULL,  40, 1),
    ('final_bill', 'ipd_number',       'IPD / Admission Number',  'text',   false, NULL, NULL,  50, 1),
    ('final_bill', 'admission_date',   'Admission Date',          'date',   false, NULL, NULL,  60, 1),
    ('final_bill', 'discharge_date',   'Discharge Date',          'date',   false, NULL, NULL,  70, 1),
    ('final_bill', 'gross_amount',     'Gross Amount',            'money',  false, NULL, NULL,  80, 1),
    ('final_bill', 'discount_amount',  'Discount',                'money',  false, NULL, NULL,  90, 1),
    ('final_bill', 'gst_amount',       'GST Amount',              'money',  false, NULL, NULL, 100, 1),
    ('final_bill', 'advance_paid',     'Advance Paid',            'money',  false, NULL, NULL, 110, 1),
    ('final_bill', 'net_amount',       'Net Amount Payable',      'money',  false, NULL, NULL, 120, 1),
    ('final_bill', 'line_item_count',  'Number of Line Items',    'number', false, NULL, NULL, 130, 1),
    ('fitness_certificate', 'certificate_date', 'Certificate Date', 'date', false, NULL, NULL, 10, 1),
    ('fitness_certificate', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 15, 1),
    ('fitness_certificate', 'patient_age', 'Patient Age', 'number', false, NULL, NULL, 20, 1),
    ('fitness_certificate', 'certifying_doctor', 'Certifying Doctor', 'text', false, NULL, NULL, 25, 1),
    ('fitness_certificate', 'doctor_registration', 'Doctor Registration No.', 'text', false, NULL, NULL, 30, 1),
    ('fitness_certificate', 'fit_for', 'Fit For (work/school/discharge)', 'text', false, NULL, NULL, 35, 1),
    ('fitness_certificate', 'diagnosis_or_reason', 'Diagnosis / Reason', 'text', false, NULL, NULL, 40, 1),
    ('fitness_certificate', 'restrictions', 'Restrictions / Conditions', 'text', false, NULL, NULL, 50, 1),
    ('fitness_certificate', 'valid_until', 'Validity Date', 'date', false, NULL, NULL, 60, 1),
    ('general_patient_photo', 'capture_timestamp', 'Photo Capture Timestamp', 'date', false, NULL, NULL, 10, 1),
    ('general_patient_photo', 'photo_purpose', 'Photo Purpose', 'enum', false, '["identity", "with_doctor", "ward", "post_op", "other"]'::jsonb, NULL, 20, 1),
    ('general_patient_photo', 'visible_text', 'Visible Text / Overlay', 'text', false, NULL, NULL, 30, 1),
    ('general_patient_photo', 'hospital_name_in_photo', 'Hospital Name (overlay)', 'text', false, NULL, NULL, 40, 1),
    ('gps_tagged_patient_photos', 'capture_timestamp', 'Photo Capture Timestamp', 'date', false, NULL, NULL, 10, 1),
    ('gps_tagged_patient_photos', 'gps_latitude', 'GPS Latitude', 'text', false, NULL, NULL, 20, 1),
    ('gps_tagged_patient_photos', 'gps_longitude', 'GPS Longitude', 'text', false, NULL, NULL, 30, 1),
    ('gps_tagged_patient_photos', 'hospital_name_in_photo', 'Hospital Name (overlay)', 'text', false, NULL, NULL, 40, 1),
    ('gps_tagged_patient_photos', 'photo_subject', 'Subject (patient/scar/site)', 'text', false, NULL, NULL, 50, 1),
    ('identity_proof', 'document_type', 'Identity Document Type', 'enum', false, '["passport", "voter_id", "drivers_licence", "pan_card", "employee_id", "other"]'::jsonb, NULL, 10, 1),
    ('identity_proof', 'document_number', 'Document Number', 'text', false, NULL, NULL, 20, 1),
    ('identity_proof', 'holder_name', 'Holder Name', 'text', false, NULL, NULL, 30, 1),
    ('identity_proof', 'date_of_birth', 'Date of Birth', 'date', false, NULL, NULL, 40, 1),
    ('identity_proof', 'issuing_authority', 'Issuing Authority', 'text', false, NULL, NULL, 50, 1),
    ('identity_proof', 'expiry_date', 'Expiry Date', 'date', false, NULL, NULL, 60, 1),
    ('implant_barcode', 'barcode_value', 'Barcode / GS1 Value', 'text', false, NULL, NULL, 10, 1),
    ('implant_barcode', 'manufacturer', 'Manufacturer', 'text', false, NULL, NULL, 20, 1),
    ('implant_barcode', 'catalog_number', 'Catalog / REF Number', 'text', false, NULL, NULL, 30, 1),
    ('implant_barcode', 'lot_number', 'Lot / Serial Number', 'text', false, NULL, NULL, 40, 1),
    ('implant_barcode', 'expiry_date', 'Expiry Date', 'date', false, NULL, NULL, 50, 1),
    ('implant_bill', 'invoice_number', 'Invoice Number', 'text', false, NULL, NULL, 10, 1),
    ('implant_bill', 'invoice_date', 'Invoice Date', 'date', false, NULL, NULL, 20, 1),
    ('implant_bill', 'vendor_name', 'Vendor / Manufacturer', 'text', false, NULL, NULL, 30, 1),
    ('implant_bill', 'implant_description', 'Implant Description', 'text', false, NULL, NULL, 40, 1),
    ('implant_bill', 'catalog_number', 'Catalog / REF Number', 'text', false, NULL, NULL, 50, 1),
    ('implant_bill', 'lot_number', 'Lot / Batch Number', 'text', false, NULL, NULL, 60, 1),
    ('implant_bill', 'unit_price', 'Unit Price', 'money', false, NULL, NULL, 70, 1),
    ('implant_bill', 'gst_amount', 'GST Amount', 'money', false, NULL, NULL, 80, 1),
    ('implant_bill', 'total_amount', 'Total Amount', 'money', false, NULL, NULL, 90, 1),
    ('implant_invoice', 'invoice_number', 'Invoice Number', 'text', false, NULL, NULL, 10, 1),
    ('implant_invoice', 'invoice_date', 'Invoice Date', 'date', false, NULL, NULL, 20, 1),
    ('implant_invoice', 'vendor_name', 'Vendor / Manufacturer', 'text', false, NULL, NULL, 30, 1),
    ('implant_invoice', 'implant_description', 'Implant Description', 'text', false, NULL, NULL, 40, 1),
    ('implant_invoice', 'catalog_number', 'Catalog / REF Number', 'text', false, NULL, NULL, 50, 1),
    ('implant_invoice', 'lot_number', 'Lot / Batch Number', 'text', false, NULL, NULL, 60, 1),
    ('implant_invoice', 'unit_price', 'Unit Price', 'money', false, NULL, NULL, 70, 1),
    ('implant_invoice', 'gst_amount', 'GST Amount', 'money', false, NULL, NULL, 80, 1),
    ('implant_invoice', 'total_amount', 'Total Amount', 'money', false, NULL, NULL, 90, 1),
    ('implant_photos', 'capture_timestamp', 'Photo Capture Timestamp', 'date', false, NULL, NULL, 10, 1),
    ('implant_photos', 'implant_type', 'Implant Type (visible)', 'text', false, NULL, NULL, 20, 1),
    ('implant_photos', 'gps_latitude', 'GPS Latitude', 'text', false, NULL, NULL, 30, 1),
    ('implant_photos', 'gps_longitude', 'GPS Longitude', 'text', false, NULL, NULL, 40, 1),
    ('implant_photos', 'visible_markings', 'Visible Markings / Branding', 'text', false, NULL, NULL, 50, 1),
    ('implant_sticker', 'manufacturer', 'Manufacturer', 'text', false, NULL, NULL, 10, 1),
    ('implant_sticker', 'model_name', 'Model / Product Name', 'text', false, NULL, NULL, 20, 1),
    ('implant_sticker', 'catalog_number', 'Catalog / REF Number', 'text', false, NULL, NULL, 30, 1),
    ('implant_sticker', 'lot_number', 'Lot / Serial Number', 'text', false, NULL, NULL, 40, 1),
    ('implant_sticker', 'size_or_spec', 'Size / Specification', 'text', false, NULL, NULL, 50, 1),
    ('implant_sticker', 'expiry_date', 'Expiry Date', 'date', false, NULL, NULL, 60, 1),
    ('implant_sticker', 'sterilisation_method', 'Sterilisation Method', 'text', false, NULL, NULL, 70, 1),
    ('investigations', 'investigation_date', 'Investigation Date', 'date', false, NULL, NULL, 10, 1),
    ('investigations', 'test_name', 'Test Name', 'text', false, NULL, NULL, 20, 1),
    ('investigations', 'test_result', 'Test Result', 'text', false, NULL, NULL, 30, 1),
    ('investigations', 'reference_range', 'Reference Range', 'text', false, NULL, NULL, 40, 1),
    ('investigations', 'abnormal_flag', 'Abnormal Flag', 'boolean', false, NULL, NULL, 50, 1),
    ('medication_administration_record', 'record_date', 'MAR Date', 'date', false, NULL, NULL, 10, 1),
    ('medication_administration_record', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 15, 1),
    ('medication_administration_record', 'prescribing_doctor', 'Prescribing Doctor', 'text', false, NULL, NULL, 20, 1),
    ('medication_administration_record', 'medications', 'Medications Administered (list)', 'text', false, NULL, NULL, 30, 1),
    ('medication_administration_record', 'antibiotics_list', 'Antibiotics', 'text', false, NULL, NULL, 40, 1),
    ('medication_administration_record', 'analgesics_list', 'Analgesics / Opioids', 'text', false, NULL, NULL, 41, 1),
    ('medication_administration_record', 'iv_fluids_list', 'IV Fluids', 'text', false, NULL, NULL, 42, 1),
    ('medication_administration_record', 'route_summary', 'Route Summary (PO/IV/IM/SC)', 'text', false, NULL, NULL, 50, 1),
    ('medication_administration_record', 'nurse_signature', 'Nurse Signature / ID', 'text', false, NULL, NULL, 60, 1),
    ('nursing_notes', 'note_date', 'Note Date', 'date', true, NULL, NULL, 10, 1),
    ('nursing_notes', 'shift', 'Shift', 'enum', false, '["MORNING", "AFTERNOON", "EVENING", "NIGHT"]'::jsonb, NULL, 20, 1),
    ('nursing_notes', 'vitals', 'Vitals', 'text', false, NULL, NULL, 30, 1),
    ('nursing_notes', 'intake_output', 'Intake / Output', 'text', false, NULL, NULL, 40, 1),
    ('nursing_notes', 'medications_administered', 'Medications Administered', 'text', false, NULL, NULL, 50, 1),
    ('nursing_notes', 'observations', 'Clinical Observations', 'text', false, NULL, NULL, 60, 1),
    ('nursing_notes', 'recorded_by', 'Recorded By', 'text', false, NULL, NULL, 70, 1),
    ('opd_notes', 'consultation_date', 'Consultation Date', 'date', false, NULL, NULL, 10, 1),
    ('opd_notes', 'consulting_doctor', 'Consulting Doctor', 'text', false, NULL, NULL, 20, 1),
    ('opd_notes', 'chief_complaints', 'Chief Complaints', 'text', true, NULL, NULL, 30, 1),
    ('opd_notes', 'history', 'Relevant History', 'text', false, NULL, NULL, 40, 1),
    ('opd_notes', 'examination_findings', 'Examination Findings', 'text', false, NULL, NULL, 50, 1),
    ('opd_notes', 'provisional_diagnosis', 'Provisional Diagnosis', 'text', false, NULL, NULL, 60, 1),
    ('opd_notes', 'investigations_ordered', 'Investigations Ordered', 'text', false, NULL, NULL, 70, 1),
    ('opd_notes', 'advice_or_plan', 'Advice / Plan', 'text', false, NULL, NULL, 80, 1),
    ('opd_notes', 'prescribed_medications', 'Prescribed Medications', 'text', false, NULL, NULL, 90, 1),
    ('others', 'document_title', 'Visible Document Title', 'text', false, NULL, NULL, 10, 1),
    ('others', 'document_date', 'Document Date', 'date', false, NULL, NULL, 20, 1),
    ('others', 'visible_summary', 'Visible Summary / Key Text', 'text', false, NULL, NULL, 30, 1),
    ('others', 'apparent_purpose', 'Apparent Purpose', 'text', false, NULL, NULL, 40, 1),
    ('ot_notes', 'surgery_date', 'Surgery Date', 'date', true, NULL, NULL, 10, 1),
    ('ot_notes', 'procedure_performed', 'Procedure Performed', 'text', true, NULL, NULL, 20, 1),
    ('ot_notes', 'surgeon', 'Surgeon', 'text', true, NULL, NULL, 30, 1),
    ('ot_notes', 'assistant_surgeons', 'Assistant Surgeon(s)', 'text', false, NULL, NULL, 40, 1),
    ('ot_notes', 'anaesthetist', 'Anaesthetist', 'text', false, NULL, NULL, 50, 1),
    ('ot_notes', 'duration_minutes', 'Duration (minutes)', 'number', false, NULL, NULL, 60, 1),
    ('ot_notes', 'anaesthesia_type', 'Anaesthesia Type', 'text', false, NULL, NULL, 70, 1),
    ('ot_notes', 'findings', 'Intra-op Findings', 'text', false, NULL, NULL, 80, 1),
    ('ot_notes', 'implants_used', 'Implants Used', 'text', false, NULL, NULL, 90, 1),
    ('ot_notes', 'complications', 'Intra-op Complications', 'text', false, NULL, NULL, 100, 1),
    ('ot_notes', 'blood_loss_ml', 'Estimated Blood Loss (ml)', 'number', false, NULL, NULL, 110, 1),
    ('ot_notes_and_photos', 'surgery_date', 'Surgery Date', 'date', true, NULL, NULL, 10, 1),
    ('ot_notes_and_photos', 'procedure_performed', 'Procedure Performed', 'text', true, NULL, NULL, 20, 1),
    ('ot_notes_and_photos', 'surgeon', 'Surgeon', 'text', true, NULL, NULL, 30, 1),
    ('ot_notes_and_photos', 'anaesthetist', 'Anaesthetist', 'text', false, NULL, NULL, 40, 1),
    ('ot_notes_and_photos', 'duration_minutes', 'Duration (minutes)', 'number', false, NULL, NULL, 50, 1),
    ('ot_notes_and_photos', 'findings', 'Findings', 'text', false, NULL, NULL, 60, 1),
    ('pathology_reports', 'report_date', 'Report Date', 'date', false, NULL, NULL, 10, 1),
    ('pathology_reports', 'specimen_type', 'Specimen Type', 'text', false, NULL, NULL, 20, 1),
    ('pathology_reports', 'tests_performed', 'Tests Performed', 'text', true, NULL, NULL, 30, 1),
    ('pathology_reports', 'key_findings', 'Key Findings', 'text', false, NULL, NULL, 40, 1),
    ('pathology_reports', 'abnormal_values', 'Abnormal Values', 'text', false, NULL, NULL, 50, 1),
    ('pathology_reports', 'impression', 'Impression', 'text', false, NULL, NULL, 60, 1),
    ('pathology_reports', 'lab_name', 'Lab Name', 'text', false, NULL, NULL, 70, 1),
    ('pathology_reports', 'pathologist', 'Reporting Pathologist', 'text', false, NULL, NULL, 80, 1),
    ('pharmacy_bill', 'bill_number', 'Bill / Invoice Number', 'text', false, NULL, NULL, 10, 1),
    ('pharmacy_bill', 'bill_date', 'Bill Date', 'date', false, NULL, NULL, 20, 1),
    ('pharmacy_bill', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 30, 1),
    ('pharmacy_bill', 'pharmacy_name', 'Pharmacy / Vendor Name', 'text', false, NULL, NULL, 40, 1),
    ('pharmacy_bill', 'gross_amount', 'Gross Amount', 'money', false, NULL, NULL, 50, 1),
    ('pharmacy_bill', 'discount_amount', 'Discount', 'money', false, NULL, NULL, 60, 1),
    ('pharmacy_bill', 'gst_amount', 'GST Amount', 'money', false, NULL, NULL, 70, 1),
    ('pharmacy_bill', 'net_amount', 'Net Amount Payable', 'money', false, NULL, NULL, 80, 1),
    ('pharmacy_bill', 'line_item_count', 'Number of Line Items', 'number', false, NULL, NULL, 90, 1),
    ('pmjay_bis_family_tree', 'pmjay_beneficiary_id', 'PMJAY Beneficiary ID', 'text', true, NULL, NULL, 10, 1),
    ('pmjay_bis_family_tree', 'household_id', 'Household ID', 'text', false, NULL, NULL, 20, 1),
    ('pmjay_bis_family_tree', 'head_of_family', 'Head of Family', 'text', true, NULL, NULL, 30, 1),
    ('pmjay_bis_family_tree', 'family_members', 'Family Members (Names)', 'text', true, NULL, NULL, 40, 1),
    ('pmjay_bis_family_tree', 'total_family_size', 'Total Family Members', 'number', false, NULL, NULL, 50, 1),
    ('pmjay_bis_family_tree', 'state', 'State', 'text', false, NULL, NULL, 60, 1),
    ('pmjay_bis_family_tree', 'district', 'District', 'text', false, NULL, NULL, 70, 1),
    ('pmjay_bis_family_tree', 'eligibility_status', 'Eligibility Status', 'enum', false, '["eligible", "not_eligible", "under_review"]'::jsonb, NULL, 80, 1),
    ('pmjay_card', 'holder_name', 'Holder Name', 'text', true, NULL, NULL, 10, 1),
    ('pmjay_card', 'date_of_birth', 'Date of Birth / YOB', 'date', false, NULL, NULL, 20, 1),
    ('pmjay_card', 'gender', 'Gender', 'enum', false, '["male", "female", "other"]'::jsonb, NULL, 30, 1),
    ('pmjay_card', 'pmjay_id', 'PM-JAY ID', 'text', false, NULL, NULL, 40, 1),
    ('pmjay_card', 'abha_number', 'ABHA Number', 'text', false, NULL, NULL, 50, 1),
    ('pmjay_card', 'village', 'Village / Town', 'text', false, NULL, NULL, 60, 1),
    ('pmjay_card', 'district', 'District', 'text', false, NULL, NULL, 70, 1),
    ('pmjay_card', 'state', 'State', 'text', false, NULL, NULL, 80, 1),
    ('pmjay_letter', 'household_head', 'Head of Household', 'text', false, NULL, NULL, 10, 1),
    ('pmjay_letter', 'family_members_count', 'Family Members Listed', 'number', false, NULL, NULL, 20, 1),
    ('pmjay_letter', 'activation_code', 'Activation Code', 'text', false, NULL, NULL, 30, 1),
    ('pmjay_letter', 'ayushman_bharat_id', 'Ayushman Bharat ID', 'text', false, NULL, NULL, 40, 1),
    ('pmjay_letter', 'state', 'State', 'text', false, NULL, NULL, 50, 1),
    ('pmjay_letter', 'district', 'District', 'text', false, NULL, NULL, 60, 1),
    ('pmjay_letter', 'helpline_number', 'Helpline Number', 'text', false, NULL, NULL, 70, 1),
    ('post_op_photos', 'capture_timestamp', 'Photo Capture Timestamp', 'date', false, NULL, NULL, 10, 1),
    ('post_op_photos', 'gps_latitude', 'GPS Latitude', 'text', false, NULL, NULL, 20, 1),
    ('post_op_photos', 'gps_longitude', 'GPS Longitude', 'text', false, NULL, NULL, 30, 1),
    ('post_op_photos', 'post_op_day', 'Post-op Day Number', 'number', false, NULL, NULL, 40, 1),
    ('post_op_photos', 'body_part_photographed', 'Body Part Photographed', 'text', false, NULL, NULL, 50, 1),
    ('post_op_photos', 'hospital_name_in_photo', 'Hospital Name (overlay)', 'text', false, NULL, NULL, 60, 1),
    ('post_op_reports', 'surgery_date', 'Surgery Date', 'date', false, NULL, NULL, 10, 1),
    ('post_op_reports', 'procedure_performed', 'Procedure Performed', 'text', false, NULL, NULL, 20, 1),
    ('post_op_reports', 'surgeon', 'Surgeon', 'text', false, NULL, NULL, 30, 1),
    ('post_op_reports', 'post_op_findings', 'Post-op Findings', 'text', false, NULL, NULL, 40, 1),
    ('post_op_reports', 'complications', 'Post-op Complications', 'text', false, NULL, NULL, 50, 1),
    ('post_op_reports', 'recovery_notes', 'Recovery / Course Notes', 'text', false, NULL, NULL, 60, 1),
    ('post_op_reports', 'follow_up_plan', 'Follow-up Plan', 'text', false, NULL, NULL, 70, 1),
    ('prescription', 'prescription_date', 'Prescription Date', 'date', false, NULL, NULL, 10, 1),
    ('prescription', 'prescribing_doctor', 'Prescribing Doctor', 'text', false, NULL, NULL, 20, 1),
    ('prescription', 'diagnosis', 'Diagnosis', 'text', false, NULL, NULL, 30, 1),
    ('prescription', 'medications', 'Medications', 'text', true, NULL, NULL, 40, 1),
    ('prescription', 'duration', 'Duration', 'text', false, NULL, NULL, 50, 1),
    ('prescription', 'follow_up_date', 'Follow-up Date', 'date', false, NULL, NULL, 60, 1),
    ('procedure_estimate', 'estimated_amount', 'Estimated Amount', 'money', true, NULL, NULL, 10, 1),
    ('procedure_estimate', 'proposed_procedure', 'Proposed Procedure', 'text', true, NULL, NULL, 20, 1),
    ('procedure_estimate', 'proposed_admission_date', 'Proposed Admission Date', 'date', false, NULL, NULL, 30, 1),
    ('procedure_estimate', 'room_category', 'Room Category', 'enum', false, '["general", "semi_private", "private", "icu", "iccu", "nicu"]'::jsonb, NULL, 40, 1),
    ('procedure_estimate', 'estimated_los_days', 'Estimated Length of Stay (days)', 'number', false, NULL, NULL, 50, 1),
    ('progress_notes', 'note_date', 'Note Date', 'date', false, NULL, NULL, 10, 1),
    ('progress_notes', 'note_time', 'Note Time', 'text', false, NULL, NULL, 11, 1),
    ('progress_notes', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 15, 1),
    ('progress_notes', 'attending_doctor', 'Attending Doctor', 'text', false, NULL, NULL, 20, 1),
    ('progress_notes', 'observations', 'Clinical Observations', 'text', false, NULL, NULL, 30, 1),
    ('progress_notes', 'vitals_bp', 'Blood Pressure (mmHg)', 'text', false, NULL, NULL, 40, 1),
    ('progress_notes', 'vitals_pulse', 'Pulse (bpm)', 'text', false, NULL, NULL, 41, 1),
    ('progress_notes', 'vitals_temp', 'Temperature', 'text', false, NULL, NULL, 42, 1),
    ('progress_notes', 'vitals_spo2', 'SpO2 (%)', 'text', false, NULL, NULL, 43, 1),
    ('progress_notes', 'assessment', 'Clinical Assessment', 'text', false, NULL, NULL, 50, 1),
    ('progress_notes', 'plan', 'Treatment Plan', 'text', false, NULL, NULL, 60, 1),
    ('progress_notes', 'investigations_today', 'Investigations Ordered', 'text', false, NULL, NULL, 70, 1),
    ('ration_card', 'ration_card_number', 'Ration Card Number', 'text', true, NULL, NULL, 10, 1),
    ('ration_card', 'card_type', 'Card Type', 'enum', true, '["APL", "BPL", "Antyodaya", "Annapurna", "Other"]'::jsonb, NULL, 20, 1),
    ('ration_card', 'head_of_family', 'Head of Family', 'text', true, NULL, NULL, 30, 1),
    ('ration_card', 'family_members', 'Family Members', 'text', false, NULL, NULL, 40, 1),
    ('ration_card', 'state', 'State', 'text', false, NULL, NULL, 50, 1),
    ('ration_card', 'district', 'District', 'text', false, NULL, NULL, 60, 1),
    ('ration_card', 'fps_shop_number', 'FPS Shop Number', 'text', false, NULL, NULL, 70, 1),
    ('ration_card', 'issue_date', 'Issue Date', 'date', false, NULL, NULL, 80, 1),
    ('serology_reports', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 10, 1),
    ('serology_reports', 'patient_age', 'Patient Age', 'number', false, NULL, NULL, 15, 1),
    ('serology_reports', 'study_date', 'Sample Date', 'date', false, NULL, NULL, 20, 1),
    ('serology_reports', 'lab_name', 'Lab Name', 'text', false, NULL, NULL, 25, 1),
    ('serology_reports', 'reporting_doctor', 'Reporting Pathologist', 'text', false, NULL, NULL, 30, 1),
    ('serology_reports', 'test_name', 'Test Name', 'text', true, NULL, NULL, 35, 1),
    ('serology_reports', 'test_value', 'Test Result', 'text', true, NULL, NULL, 40, 1),
    ('serology_reports', 'reference_range', 'Reference Range', 'text', false, NULL, NULL, 45, 1),
    ('serology_reports', 'result_flag', 'Flag (Normal/High/Low/Reactive/Non-reactive)', 'text', false, NULL, NULL, 50, 1),
    ('serology_reports', 'methodology', 'Methodology', 'text', false, NULL, NULL, 55, 1),
    ('surgery_consent_form', 'consent_date', 'Consent Date', 'date', false, NULL, NULL, 10, 1),
    ('surgery_consent_form', 'procedure_planned', 'Planned Procedure', 'text', false, NULL, NULL, 20, 1),
    ('surgery_consent_form', 'surgeon_name', 'Surgeon Name', 'text', false, NULL, NULL, 30, 1),
    ('surgery_consent_form', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 40, 1),
    ('surgery_consent_form', 'signed_by', 'Signed By', 'text', false, NULL, NULL, 50, 1),
    ('surgery_consent_form', 'relationship_to_patient', 'Relationship to Patient', 'text', false, NULL, NULL, 60, 1),
    ('surgery_consent_form', 'risks_discussed', 'Risks Discussed', 'text', false, NULL, NULL, 70, 1),
    ('surgery_consent_form', 'witness_name', 'Witness Name', 'text', false, NULL, NULL, 80, 1),
    ('surgical_discharge_slip', 'admission_date', 'Admission Date', 'date', true, NULL, NULL, 10, 1),
    ('surgical_discharge_slip', 'discharge_date', 'Discharge Date', 'date', true, NULL, NULL, 20, 1),
    ('surgical_discharge_slip', 'primary_diagnosis', 'Primary Diagnosis', 'text', true, NULL, NULL, 30, 1),
    ('surgical_discharge_slip', 'procedure_performed', 'Procedure Performed', 'text', true, NULL, NULL, 40, 1),
    ('surgical_discharge_slip', 'surgery_date', 'Surgery Date', 'date', false, NULL, NULL, 45, 1),
    ('surgical_discharge_slip', 'primary_surgeon', 'Primary Surgeon', 'text', false, NULL, NULL, 50, 1),
    ('surgical_discharge_slip', 'anaesthetist', 'Anaesthetist', 'text', false, NULL, NULL, 60, 1),
    ('surgical_discharge_slip', 'anaesthesia_type', 'Anaesthesia Type', 'enum', false, '["GENERAL", "SPINAL", "EPIDURAL", "REGIONAL", "LOCAL", "SEDATION"]'::jsonb, NULL, 70, 1),
    ('surgical_discharge_slip', 'implants_used', 'Implants Used', 'text', false, NULL, NULL, 80, 1),
    ('surgical_discharge_slip', 'operative_findings', 'Operative Findings', 'text', false, NULL, NULL, 90, 1),
    ('surgical_discharge_slip', 'post_op_course', 'Post-op Course', 'text', false, NULL, NULL, 100, 1),
    ('surgical_discharge_slip', 'discharge_condition', 'Condition at Discharge', 'text', false, NULL, NULL, 110, 1),
    ('surgical_discharge_slip', 'discharge_medications', 'Discharge Medications', 'text', false, NULL, NULL, 120, 1),
    ('surgical_discharge_slip', 'follow_up_advice', 'Follow-up Advice', 'text', false, NULL, NULL, 130, 1),
    ('surgical_discharge_slip', 'treating_doctor', 'Treating Doctor', 'text', false, NULL, NULL, 140, 1),
    ('surgical_discharge_slip', 'room_category', 'Room Category', 'enum', false, '["general", "semi_private", "private", "icu", "iccu", "nicu"]'::jsonb, NULL, 150, 1),
    ('xray_reports', 'patient_name', 'Patient Name', 'text', false, NULL, NULL, 10, 1),
    ('xray_reports', 'patient_age', 'Patient Age', 'number', false, NULL, NULL, 15, 1),
    ('xray_reports', 'patient_sex', 'Patient Sex', 'enum', false, '["M", "F", "O"]'::jsonb, NULL, 16, 1),
    ('xray_reports', 'study_date', 'Study Date', 'date', false, NULL, NULL, 20, 1),
    ('xray_reports', 'body_part', 'Body Part / Anatomy', 'text', true, NULL, NULL, 30, 1),
    ('xray_reports', 'views', 'Views (AP / Lateral / Oblique)', 'text', false, NULL, NULL, 40, 1),
    ('xray_reports', 'laterality', 'Laterality', 'enum', false, '["LEFT", "RIGHT", "BILATERAL", "NA"]'::jsonb, NULL, 45, 1),
    ('xray_reports', 'imaging_centre', 'Imaging Centre / Hospital', 'text', false, NULL, NULL, 50, 1),
    ('xray_reports', 'findings', 'Findings', 'text', false, NULL, NULL, 60, 1),
    ('xray_reports', 'impression', 'Impression', 'text', false, NULL, NULL, 70, 1),
    ('xray_reports', 'ordering_physician', 'Ordering Physician', 'text', false, NULL, NULL, 80, 1),
    ('xray_reports', 'reporting_radiologist', 'Reporting Radiologist', 'text', false, NULL, NULL, 90, 1)
ON CONFLICT (doc_category, field_key, schema_version) DO UPDATE SET
    field_label         = EXCLUDED.field_label,
    field_type          = EXCLUDED.field_type,
    is_required         = EXCLUDED.is_required,
    enum_values         = EXCLUDED.enum_values,
    reference_category  = EXCLUDED.reference_category,
    extraction_priority = EXCLUDED.extraction_priority;

