-- ==========================================================================
-- 050 — attribute_definitions (the hospital attribute catalog)
-- ==========================================================================
-- Applied by src/schema/run-seeds.cjs, which owns the transaction and records
-- this file's sha256 in hospital.seed_applications. Editing the file changes
-- that checksum, which is exactly what makes the next `npm run seed` re-apply
-- it. See seeds/README.md for the authoring rules the CI guard enforces.
--
-- This is a DECLARATIVE snapshot of the desired catalog, not a replay of
-- history: it was generated from a database that had run every migration in
-- order, so it is the union of the sources below with every later rename,
-- relabel and correction already folded in.
--
-- Historical sources (left untouched in migrations/, which production is
-- already stamped for):
--   002c_attribute_definitions_seed.sql
--   002c_fixed.sql
--
-- The two source migrations are competing variants of the same catalog and both
-- used DO NOTHING, so whichever ran first won every field. This snapshot is the
-- merged result, and DO UPDATE makes later corrections propagate.
-- ==========================================================================

INSERT INTO hospital.attribute_definitions
    (key, category, label, description, data_type, unit, requires_document, has_expiry,
     expected_issuing_authority, can_verify_by_image, image_guidance,
     is_mandatory_basic, is_mandatory_empanelment, sort_order, is_active) VALUES
    ('accreditation.nabh_full', 'accreditation', 'NABH Full Accreditation', 'National Accreditation Board for Hospitals — Full', 'document', NULL, true, true, 'NABH', false, NULL, false, false, 10, true),
    ('accreditation.nabh_entry', 'accreditation', 'NABH Entry Level', 'NABH Entry Level Certification', 'document', NULL, true, true, 'NABH', false, NULL, false, false, 11, true),
    ('accreditation.jci', 'accreditation', 'JCI Accreditation', 'Joint Commission International', 'document', NULL, true, true, 'Joint Commission International', false, NULL, false, false, 12, true),
    ('accreditation.nabl', 'accreditation', 'NABL Lab Accreditation', 'National Accreditation Board for Testing and Calibration Laboratories', 'document', NULL, true, true, 'NABL', false, NULL, false, false, 13, true),
    ('accreditation.cghs', 'accreditation', 'CGHS Empanelment', 'Central Government Health Scheme empanelment', 'document', NULL, true, true, 'CGHS', false, NULL, false, false, 14, true),
    ('accreditation.state_govt', 'accreditation', 'State Govt Registration', 'Registration certificate from State Health Department', 'document', NULL, true, true, NULL, false, NULL, true, true, 15, true),
    ('accreditation.min_of_health', 'accreditation', 'Ministry of Health', 'Central Ministry of Health and Family Welfare', 'document', NULL, true, true, 'MoHFW', false, NULL, false, false, 16, true),
    ('accreditation.iso_9001', 'accreditation', 'ISO 9001 Certification', 'ISO 9001 Quality Management System', 'document', NULL, true, true, NULL, false, NULL, false, false, 17, true),
    ('compliance_cert.fire_noc', 'compliance_cert', 'Fire NOC', 'No Objection Certificate from Fire Department', 'document', NULL, true, true, NULL, false, NULL, true, true, 20, true),
    ('compliance_cert.biomedical_waste', 'compliance_cert', 'Biomedical Waste Authorization', 'Authorization from State Pollution Control Board for biomedical waste handling', 'document', NULL, true, true, NULL, false, NULL, true, true, 21, true),
    ('compliance_cert.clinical_est_lic', 'compliance_cert', 'Clinical Establishment License', 'License under Clinical Establishments (Registration and Regulation) Act', 'document', NULL, true, true, NULL, false, NULL, true, true, 22, true),
    ('compliance_cert.pcpndt_license', 'compliance_cert', 'PCPNDT License', 'Pre-Conception and Pre-Natal Diagnostic Techniques Act license (if applicable)', 'document', NULL, true, true, NULL, false, NULL, false, false, 23, true),
    ('compliance_cert.lift_inspection', 'compliance_cert', 'Lift Inspection Certificate', 'Annual inspection certificate for passenger lifts from State Electrical Inspectorate', 'document', NULL, true, true, NULL, false, NULL, false, false, 24, true),
    ('compliance_cert.blood_bank_license', 'compliance_cert', 'Blood Bank License', 'License from Drug Controller for operating blood bank', 'document', NULL, true, true, NULL, false, NULL, false, false, 25, true),
    ('compliance_cert.pharmacy_license', 'compliance_cert', 'Pharmacy License', 'Drug license for operating in-house pharmacy', 'document', NULL, true, true, NULL, false, NULL, false, false, 26, true),
    ('compliance_cert.water_test_report', 'compliance_cert', 'Water Quality Test Report', 'Recent water quality testing report from accredited lab', 'document', NULL, true, true, NULL, false, NULL, false, false, 27, true),
    ('compliance_cert.boiler_cert', 'compliance_cert', 'Boiler/Pressure Vessel Cert', 'Annual safety certificate for boilers and pressure vessels', 'document', NULL, true, true, NULL, false, NULL, false, false, 28, true),
    ('compliance_policy.infection_control', 'compliance_policy', 'Infection Control Policy', 'Documented hospital infection control policy', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 30, true),
    ('compliance_policy.waste_management', 'compliance_policy', 'Waste Management System', 'Documented medical waste management and disposal system', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 31, true),
    ('compliance_policy.hims', 'compliance_policy', 'Hospital Information Mgmt System', 'Hospital Information Management System operational', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 32, true),
    ('compliance_policy.coding_practices', 'compliance_policy', 'Medical Coding Practices', 'Coding practices followed: ICD 09, ICD 10, CPT, PCS or other', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 33, true),
    ('compliance_policy.record_archiving', 'compliance_policy', 'Record Storage and Archiving', 'Documented system for medical record storage and archiving', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 34, true),
    ('compliance_policy.tpa_connectivity', 'compliance_policy', 'TPA Online Connectivity', 'Capability to connect online with Insurer/TPA for pre-authorization and document submission', 'boolean', NULL, false, false, NULL, false, NULL, false, true, 35, true),
    ('infrastructure.generator_backup', 'infrastructure', 'Full Generator Back-up', 'Dedicated generator providing full hospital backup power', 'boolean', NULL, false, false, NULL, true, 'Upload photo of generator room showing nameplate with KVA capacity', false, false, 40, true),
    ('infrastructure.ramp_availability', 'infrastructure', 'Ramp for Disabled Access', 'Wheelchair ramp or accessible entry for disabled patients — verifiable by photo', 'boolean', NULL, false, false, NULL, true, 'Take clear photo of ramp at main entrance', false, false, 40, true),
    ('infrastructure.lift', 'infrastructure', 'Lifts Available', 'Passenger/goods lifts accessible to patients', 'boolean', NULL, false, false, NULL, true, 'Upload photo of lift interior showing capacity plate and latest inspection certificate displayed', false, false, 41, true),
    ('infrastructure.lift_available', 'infrastructure', 'Elevator/Lift Access', 'Functional elevator for patient movement between floors', 'boolean', NULL, false, false, NULL, true, 'Photo of working elevator', false, false, 41, true),
    ('infrastructure.ramp', 'infrastructure', 'Ramp Availability', 'Wheelchair-accessible ramp for patient mobility', 'boolean', NULL, false, false, NULL, true, 'Upload photo of ramp showing full length, slope, and handrails clearly', false, false, 42, true),
    ('infrastructure.backup_power', 'infrastructure', 'Backup Power Generator', 'Backup power generation facility for uninterrupted operations', 'boolean', NULL, false, false, NULL, true, 'Photo of generator and maintenance records', false, false, 43, true),
    ('infrastructure.parking_capacity', 'infrastructure', 'Parking Capacity', 'Number of vehicles the parking area can accommodate', 'integer', 'vehicles', false, false, NULL, true, 'Upload photo of parking area with capacity signage visible', false, false, 43, true),
    ('infrastructure.central_gas', 'infrastructure', 'Central Gas Supply', 'Centralized medical gas supply system', 'boolean', NULL, false, false, NULL, true, 'Upload photo of central gas manifold/pipeline installation', false, false, 44, true),
    ('infrastructure.cssd', 'infrastructure', 'Central Sterile Services Dept', 'Dedicated CSSD for sterilization of surgical instruments', 'boolean', NULL, false, false, NULL, true, 'Upload photo of CSSD area with autoclave equipment visible', false, false, 45, true),
    ('infrastructure.air_conditioning', 'infrastructure', 'Fully Air-Conditioned', 'All patient areas are air-conditioned', 'boolean', NULL, false, false, NULL, true, 'Upload photo showing AC units in ward/room', false, false, 46, true),
    ('infrastructure.kitchen_canteen', 'infrastructure', 'In-House Kitchen & Canteen', 'Dedicated in-house kitchen and patient/staff canteen', 'boolean', NULL, false, false, NULL, true, 'Upload photo of kitchen facility', false, false, 47, true),
    ('infrastructure.housekeeping', 'infrastructure', 'Housekeeping & Laundry', 'In-house housekeeping and laundry services', 'boolean', NULL, false, false, NULL, true, 'Upload photo of laundry facility', false, false, 48, true),
    ('infrastructure.fire_system', 'infrastructure', 'Fire Protection System', 'Installed fire protection system (sprinklers, fire extinguishers, fire panel)', 'boolean', NULL, false, false, NULL, true, 'Upload photo of fire panel/sprinkler heads/extinguisher locations', false, false, 49, true),
    ('beds.general_wards_total', 'beds', 'General Ward Beds', 'Total number of general ward beds', 'integer', 'count', false, false, NULL, false, NULL, false, false, 50, true),
    ('infrastructure.water_purification', 'infrastructure', 'Water Purification & Filtration', 'Water purification and filtration system for potable water', 'boolean', NULL, false, false, NULL, true, 'Upload photo of water purification equipment', false, false, 50, true),
    ('beds.private_rooms', 'beds', 'Private Room Beds', 'Total number of private room beds', 'integer', 'count', false, false, NULL, false, NULL, false, false, 51, true),
    ('infrastructure.gas_plant', 'infrastructure', 'Gas Plant/Boiler/Sterilizers', 'On-site gas plant, steam boiler, or industrial sterilizers', 'boolean', NULL, false, false, NULL, true, 'Upload photo of boiler/gas plant', false, false, 51, true),
    ('in_house.blood_bank', 'in_house', 'Blood Bank', 'Licensed in-house blood bank', 'boolean', NULL, false, false, NULL, true, 'Upload photo of blood bank area', false, false, 55, true),
    ('in_house.ambulance', 'in_house', 'Ambulance', 'Hospital-operated ambulance service', 'boolean', NULL, false, false, NULL, true, 'Upload photo of ambulance', false, false, 56, true),
    ('in_house.pharmacy', 'in_house', 'In-House Pharmacy', 'Licensed in-house pharmacy', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 57, true),
    ('in_house.defibrillator', 'in_house', 'Defibrillator', 'Defibrillator(s) available', 'boolean', NULL, false, false, NULL, true, 'Upload photo of defibrillator unit', false, false, 58, true),
    ('in_house.o2_supply', 'in_house', 'Oxygen Supply', 'Centralized or bedside oxygen supply', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 59, true),
    ('beds.general_ward', 'beds', 'General Ward Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, true, true, 60, true),
    ('icu.icu_beds_total', 'icu', 'ICU Beds', 'Total number of Intensive Care Unit beds', 'integer', 'count', false, false, NULL, false, NULL, false, false, 60, true),
    ('beds.sharing', 'beds', 'Sharing Room Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 61, true),
    ('beds.private', 'beds', 'Private Room Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 62, true),
    ('icu.ventilators', 'icu', 'Ventilators', 'Number of ventilators available', 'integer', 'count', false, false, NULL, false, NULL, false, false, 62, true),
    ('beds.deluxe', 'beds', 'Deluxe Room Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 63, true),
    ('beds.burns', 'beds', 'Burns Unit Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 64, true),
    ('icu.micu', 'icu', 'MICU Beds (Medical ICU)', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 70, true),
    ('ot.operation_theaters', 'ot', 'Operation Theaters', 'Total number of operational OTs', 'integer', 'count', false, false, NULL, false, NULL, false, false, 70, true),
    ('icu.iccu', 'icu', 'ICCU Beds (Cardiac Care)', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 71, true),
    ('icu.nicu', 'icu', 'NICU Beds (Neonatal)', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 72, true),
    ('icu.picu', 'icu', 'PICU Beds (Paediatric)', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 73, true),
    ('icu.neuro', 'icu', 'Neuro ICU Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 74, true),
    ('icu.sicu', 'icu', 'SICU Beds (Surgical)', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 75, true),
    ('equipment.mri_machine', 'equipment', 'MRI Machine', 'Magnetic Resonance Imaging machine', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 80, true),
    ('ot.emergency_room', 'ot', 'Emergency Room Beds', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 80, true),
    ('equipment.ct_scanner', 'equipment', 'CT Scanner', 'Computed Tomography Scanner', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 81, true),
    ('ot.trauma', 'ot', 'Trauma Bays', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 81, true),
    ('equipment.ultrasound', 'equipment', 'Ultrasound Machine', 'Ultrasound diagnostic equipment', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 82, true),
    ('ot.minor_ot', 'ot', 'Minor OT', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 82, true),
    ('ot.major_ot', 'ot', 'Major OT', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 83, true),
    ('ot.cath_lab', 'ot', 'Cath Lab', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 84, true),
    ('equipment.ventilator', 'equipment', 'Ventilator', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of ventilator equipment area', false, false, 90, true),
    ('lab.blood_bank', 'lab', 'Blood Bank', 'In-house blood bank facility', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 90, true),
    ('equipment.c_arm', 'equipment', 'C-Arm', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of C-Arm machine', false, false, 91, true),
    ('lab.biochemistry_lab', 'lab', 'Biochemistry Lab', 'Laboratory for biochemical tests', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 91, true),
    ('equipment.ct_scan', 'equipment', 'CT Scan', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of CT scanner', false, false, 92, true),
    ('equipment.mri', 'equipment', 'MRI', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of MRI machine', false, false, 93, true),
    ('equipment.pet_ct', 'equipment', 'PET CT', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of PET CT machine', false, false, 94, true),
    ('equipment.angiography', 'equipment', 'Angiography Machine', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of angiography suite', false, false, 95, true),
    ('equipment.usg', 'equipment', 'USG Machine', NULL, 'integer', 'count', false, false, NULL, true, NULL, false, false, 96, true),
    ('equipment.echo', 'equipment', 'Echo Machine', NULL, 'integer', 'count', false, false, NULL, true, NULL, false, false, 97, true),
    ('equipment.tmt', 'equipment', 'TMT Machine', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 98, true),
    ('equipment.holter', 'equipment', 'Holter Monitor', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 99, true),
    ('equipment.iabp', 'equipment', 'IABP', 'Intra-Aortic Balloon Pump', 'integer', 'count', false, false, NULL, false, NULL, false, false, 100, true),
    ('service.cardiology', 'service', 'Cardiology Department', 'Cardiac care and intervention services', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 100, true),
    ('equipment.linear_accelerator', 'equipment', 'Linear Accelerator', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of LINAC machine', false, false, 101, true),
    ('equipment.brachytherapy', 'equipment', 'Brachytherapy', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 102, true),
    ('service.pediatrics', 'service', 'Pediatrics Department', 'Pediatric care services', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 102, true),
    ('equipment.gamma_knife', 'equipment', 'Gamma Knife', NULL, 'integer', 'count', false, false, NULL, true, 'Upload photo of Gamma Knife unit', false, false, 103, true),
    ('service.emergency', 'service', 'Emergency Department', '24/7 Emergency care facility', 'boolean', NULL, false, false, NULL, false, NULL, false, false, 104, true),
    ('lab.hematology', 'lab', 'Hematology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 110, true),
    ('lab.biochemistry', 'lab', 'Biochemistry Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 111, true),
    ('lab.pathology', 'lab', 'Pathology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 112, true),
    ('lab.microbiology', 'lab', 'Microbiology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 113, true),
    ('lab.virology', 'lab', 'Virology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 114, true),
    ('lab.serology', 'lab', 'Serology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 115, true),
    ('lab.immunology', 'lab', 'Immunology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 116, true),
    ('lab.histopathology', 'lab', 'Histopathology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 117, true),
    ('lab.cytology', 'lab', 'Cytology Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 118, true),
    ('lab.genetics', 'lab', 'Genetics Lab', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 119, true),
    ('lab.radiology_xray', 'lab', 'X-Ray', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 120, true),
    ('lab.nuclear_medicine', 'lab', 'Nuclear Medicine', NULL, 'boolean', NULL, false, false, NULL, false, NULL, false, false, 121, true),
    ('staffing.resident_doctors', 'staffing', 'Resident Doctors', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 130, true),
    ('staffing.specialists', 'staffing', 'Specialist Doctors', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 131, true),
    ('staffing.visiting', 'staffing', 'Visiting Consultants', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 132, true),
    ('staffing.nursing', 'staffing', 'Nursing Staff', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 133, true),
    ('staffing.paramedical', 'staffing', 'Paramedical Staff', NULL, 'integer', 'count', false, false, NULL, false, NULL, false, false, 134, true),
    ('room_rent.general_ward', 'room_rent', 'General Ward Rate', 'Daily room rent for general ward', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 140, true),
    ('room_rent.sharing', 'room_rent', 'Sharing Room Rate', 'Daily room rent for sharing room', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 141, true),
    ('room_rent.private', 'room_rent', 'Private Room Rate', 'Daily room rent for private room', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 142, true),
    ('room_rent.deluxe', 'room_rent', 'Deluxe Room Rate', 'Daily room rent for deluxe room', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 143, true),
    ('room_rent.icu', 'room_rent', 'ICU Daily Rate', 'Daily charge for ICU bed', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 144, true),
    ('room_rent.iccu', 'room_rent', 'ICCU Daily Rate', 'Daily charge for ICCU bed', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 145, true),
    ('room_rent.nicu', 'room_rent', 'NICU Daily Rate', 'Daily charge for NICU bed', 'integer', 'INR/day', false, false, NULL, false, NULL, false, false, 146, true)
ON CONFLICT (key) DO UPDATE SET
    category                   = EXCLUDED.category,
    label                      = EXCLUDED.label,
    description                = EXCLUDED.description,
    data_type                  = EXCLUDED.data_type,
    unit                       = EXCLUDED.unit,
    requires_document          = EXCLUDED.requires_document,
    has_expiry                 = EXCLUDED.has_expiry,
    expected_issuing_authority = EXCLUDED.expected_issuing_authority,
    can_verify_by_image        = EXCLUDED.can_verify_by_image,
    image_guidance             = EXCLUDED.image_guidance,
    is_mandatory_basic         = EXCLUDED.is_mandatory_basic,
    is_mandatory_empanelment   = EXCLUDED.is_mandatory_empanelment,
    sort_order                 = EXCLUDED.sort_order,
    is_active                  = EXCLUDED.is_active,
    updated_at                 = NOW();

