-- ============================================================================
-- Wave 9 follow-up — per-category extraction routing (OCR vs Claude vision).
-- ============================================================================
-- Tesseract OCR works well for typed text (bills, computer-generated discharge
-- summaries, structured reports), but it fails badly on:
--   - Handwritten doctor's notes / progress notes
--   - OT (operative) notes (mix of handwriting + diagrams + stamps)
--   - Radiology images (X-ray plates with annotations)
--   - Faint stamps / signatures
--   - Multi-column lab reports with rotated text
--
-- Claude (Sonnet vision) reads all of these natively — we've verified this by
-- pasting the same images into the Claude UI and getting clean structured
-- output. The extractor pipeline today never invokes vision; it always
-- routes OCR'd text to a text-only LLM call.
--
-- This migration adds an `extraction_mode` column to master_options for the
-- doc_category vocabulary. Three valid modes:
--
--   'ocr'    (default) — Tesseract → text → text-only LLM call.
--                        Cheapest. Right for typed docs.
--   'vision' — Skip Tesseract. Send the image bytes directly to Claude
--              vision. ~10× the token cost of text but correct on
--              handwriting, X-rays, faint scans.
--   'auto'   — Try OCR first. If Tesseract confidence < 0.3 AND the OCR
--              text has < 50 alphanumeric chars, escalate to vision.
--              Good middle ground for categories that are mixed
--              (some typed, some handwritten).
--
-- We don't set vision globally — it would 10× cost on every claim. We set it
-- only on categories where we know the OCR pipeline is unreliable. New
-- vision-routed categories can be added by superadmin editing the value
-- directly in master_options.
--
-- The default for existing rows is 'ocr' so no behaviour change for the 90%
-- of categories that work fine with Tesseract.
--
-- ── BOTH UPDATES BELOW ARE GUARDED `AND extraction_mode IS NULL` ───────────
--
-- THE RULE (see seeds/README.md § "extraction_mode is operator-owned", and
-- migration 052, which was fixed the same way):
--   A non-NULL master_options.extraction_mode is OPERATOR INTENT and is never
--   overwritten by an automated re-run — not by `npm run seed`, not by a
--   migration replay.
--
-- Why this file needed it too. `extraction_mode` is a live COST dial: it
-- decides, per document category, whether a page goes to Tesseract or to a
-- per-page Claude Vision call. Both statements below were written as
-- unconditional re-assertions, so replaying this file (a fresh `db:bootstrap`
-- against a database that already has data, a ledger reconciliation that
-- re-runs 050, a restore-then-migrate) silently reverted every category an
-- operator had pinned to 'ocr' for cost control — a cost regression shipped by
-- a data migration. The guard makes each statement falsify its own predicate:
-- the row it fills no longer matches, so a replay touches nothing.
--
-- The guard does NOT change what a fresh bootstrap produces. This migration
-- runs against a catalog whose extraction_mode column it has just ADDED (the
-- ALTER below), so every row is NULL when the first UPDATE runs, and the two
-- code lists are disjoint — no code is set by the 'vision' statement and then
-- re-read by the 'auto' one. First-run output is byte-identical either way.
--
-- To deliberately re-route a category fleet-wide AFTER an environment already
-- has a value, do not edit this file and do not edit the seed's mode column:
-- ship a NEW numbered migration that names the categories it changes. That is
-- the only path allowed to overwrite an existing value, and it leaves a
-- reviewable record of doing so.

BEGIN;

ALTER TABLE hospital.master_options
  ADD COLUMN IF NOT EXISTS extraction_mode VARCHAR(16);

-- Add a soft CHECK constraint via a deferred check (kept loose so future
-- modes — e.g. 'auto_with_skew_detect' — can be added without an
-- ALTER COLUMN). Enforced at the service layer.
COMMENT ON COLUMN hospital.master_options.extraction_mode IS
  'Per-category extraction routing for doc_category rows: ocr | vision | auto. Null = ocr (default). Read by docExtractor.service.ts.';

-- Categories we KNOW Tesseract is bad at — route directly to Claude vision.
UPDATE hospital.master_options
   SET extraction_mode = 'vision'
 WHERE category = 'doc_category'
   AND code IN (
     -- Operative notes are handwritten on a standard form with diagrams,
     -- stamps, and signatures. Tesseract returns 5-15% confidence reliably.
     'ot_notes_and_photos',
     -- Anaesthesia notes are similar — handwritten chart with grids.
     'anaesthesia_consent',
     'anesthesia_record',
     -- Discharge slips at small nursing homes are still hand-written.
     'surgical_discharge_slip',
     -- Daily progress notes — pure handwriting.
     'daily_progress_notes',
     'icu_charts',
     'nursing_notes',
     -- Radiology reports — when the report is image-only (X-ray plate
     -- with hand-annotated impression) Tesseract fails. Typed PACS reports
     -- still work via OCR — we use 'auto' so the cheap path tries first.
     'xray_reports',
     'ct_scan_reports',
     'mri_reports',
     -- Prescriptions are notoriously hand-scribbled.
     'opd_prescription',
     'prescription'
   )
   AND extraction_mode IS NULL;

-- Categories where it's a coin flip — try OCR first, escalate if needed.
UPDATE hospital.master_options
   SET extraction_mode = 'auto'
 WHERE category = 'doc_category'
   AND code IN (
     'admission_notes',
     'pathology_reports',
     'ecg_reports',
     'echo_reports'
   )
   AND extraction_mode IS NULL;

COMMIT;
